
CREATE TABLE ratings (
	worker_id INT NOT NULL,
	customer_id INT NOT NULL,
	rate_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	identifier VARCHAR(255) NOT NULL DEFAULT (UUID()),
	rate VARCHAR(255) NOT NULL,
	description VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (worker_id, customer_id, rate_date)
);



