
apiVersion: v1
kind: Namespace
metadata:
  name: cita-dev-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cita-backend-app
  namespace: cita-dev-ns
  labels:
    app: cita-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cita-backend-app
  template:
    metadata:
      labels:
        app: cita-backend-app
    spec:
      containers:
        - name: cita-backend-app
          image: selimhorri/cita-backend-app:dev
          imagePullPolicy: IfNotPresent
          #readinessProbe: 
          #  httpGet: 
          #    path: /actuator/health/readiness
          #    port: 8400
          #  initialDelaySeconds: 15
          #  periodSeconds: 30
          #  failureThreshold: 3
          #livenessProbe: 
          #  httpGet: 
          #    path: /actuator/health/liveness
          #    port: 8400
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          #  failureThreshold: 3
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8400
          env:
            - name: APP_SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_NAME
            - name: APP_SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_MAIL_USERNAME
            - name: APP_SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_MAIL_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: cita-backend-app-service
  namespace: cita-dev-ns
spec:
  selector:
    app: cita-backend-app
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
      #nodePort: 30001






