
INSERT INTO locations (zipCode,city,state) VALUES ('2080','ariana','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite des roses','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','centre commercial ikram','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite du jardin','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','cite ennasr 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite du printemps','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','cite ennasr 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite ennouzha','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','el menzah 7','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite essaada (ariana)','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','el menzah 8','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','cite jaafar','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','residence ennour ( naser 1)','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','nouvelle ariana','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2037','residence ennour ( naser 2)','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2080','residence ennour (ariana)','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','cite belvedere 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','cite du soleil','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','cite el intissar 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','cite el intissar 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','cite jamil','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','el menzah 5','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2091','el menzah 6','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite borj turki 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite borj turki 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2027','borj el baccouche','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite de la sante','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite essaada (riadh andalous)','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite karim','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','cite mehrzia 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','residence el ouns','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','residence ibn zeidoun','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','residence ichbilia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','residence kortoba','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2058','riadh landlous','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite 18 janvier','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite ben yerfes','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite el houda','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite ennasser','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite ettadhamen','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite ettayarene','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite sfar','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite snit 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2041','cite snit nagra','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','borj el hadj','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','el misra','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','ferme hababou','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','ferme mustapha','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','henchir touba','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','henchir toubias','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2061','pont de bizerte','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite bir el araies','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite des martyrs','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite el fejja','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite el mourouj','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite el oulja','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite essibous','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','cite tarek ibn zied','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2022','kalaat landlous','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite fateh','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite fonciere','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite snit','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite touilia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','dar fadhal','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','la soukra','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','mosque erraoudha','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','residence 26-26','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','residence ahlem','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','residence meriem','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','sidi frej','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','sidi salah','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','sidi soufiene','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','village essahli','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','borj louzir','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite ben kilani','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite de la sante','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2035','aeroport tunis carthage','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite el behi ladghem','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2035','charguia 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite el feth','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2035','charguia 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite el hana','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2035','station marchandises fret','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite el mansoura','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite el ouroud','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','chotrana 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite ennacim','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','chotrana 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite ennouzha 3','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','chotrana 3','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite ettaamir 5','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite astree','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite ghouzaila','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite belabla','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite hedi nouira','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite ben hessine','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite jebira','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite bou fares','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite snit','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite chouachia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','cite star','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite chouchene','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','residence el ouns','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite de l''aeroport','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2073','residence ennesrine','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite de la terre libre','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite des juges','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite el azzef','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite el boustene 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite el boustene 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite el henaya','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite el maid','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite elyes','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite ettaamir','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite ezzitoun 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite ezzitoun 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite ezzouaidia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2036','cite farhat','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite ali bourguiba','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite de la republique','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite el bassatine1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite el bassatine2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite el bassatine3','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite el gouabsia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite el ouard','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite ennasr','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite essaada','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite rafaha','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','cite rous el harayek','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','essanhaji','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','mnihla','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2094','residence ennasr','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite el mouaouiet','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite el mountazeh','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite ennour jaafar','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2088','complexe technologique','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite erriadh','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite essaada','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite sidi slimene','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite snit','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','douar el hendi','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','el hessiene','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','oued el khayat','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','oued el makhzen','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','residence el ayech','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','residence el ouns','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','residence ennarjes','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','residence essalem','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','residence rim','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','route ezzaouia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','ariana essoughra','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','borj touil','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite chaker','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','bou hnech','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2081','cite de la mosque','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite 7 novembre','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite aeroport','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite chargui','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite des juges','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite el yamama','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite sidi salah','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','cite zghab','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','el brarja','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2056','raoued','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite de la rtt 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite el abadla','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite el amel','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite el ghazala 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite el ghazala 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite el wafa','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite ennasr','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite ennkhilet','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite essahafa','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite ibn rachik','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','cite mehrzia 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','jaafar 1','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2083','jaafar 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite dridi','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite el bokri','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite el frachich','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite el ghribi','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite el methalithe','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite messouda','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite ouvriere','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cite sidi marouane','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','ezzaouia','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','bejaoua 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','jabbes','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite 18 janvier','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','jabbes el borj','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite afh','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite des agriculteurs','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite des oranges','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite el gouazine','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite el mbarka','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite el mrezgua','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite essaada','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite ettbaieb','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite jardins','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','cite mongi slim','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2020','sidi thabet','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2057','chorfech','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2057','chorfech 2','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2057','chorfech 24','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2057','chorfech 8','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','borj el khoukha','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','borj youssef','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','cebalet ben ammar','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('2032','chorfech 12','ariana');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','ain el goussa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','ain ghenem','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','beni melek','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','bouris','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','cite de la poste','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','cite erraoudha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','cite hached','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','cite taieb mhiri','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','eddghabjia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','edhhirat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el fraijia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el ghorfa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el graia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el hlikat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el jouza','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','el mjales','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','gaat el mouhdi','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','ghouzia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','maghraoua','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','menzel hammed','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','remadhnia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9084','el ayayda','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','sidi mbarek','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9084','el homr','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','sidi saadoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9084','menzel el gourchi','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','sobah','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','zahret mediene','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9030','adailia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el habibia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el haouari','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el khadhra','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el khadhra superieur','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el manar 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el manar 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el manar 3','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el manar 4','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el manar 5','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el mekmda','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el mhella','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el moustakbel','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el mzara','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el olfa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ennouzha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite erriadh 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite erriadhi 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite essalama','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite essalem','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite essanaouber','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ezzouhour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite garde nationale','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ibn khaldoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite jardins','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite jebel el akhdhar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ksar bardo','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9031','el mzara','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite pont trageon','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite s.r.transport','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite salah el maghraoui','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite salambo','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite sidi frej','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite snit','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite taieb mhiri','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite usine du sucre1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','ain ksar hadid','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite usine du sucre2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','beja','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','el hamrounia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','bou keslane','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','el mounchar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','charchara','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','el yousri','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite afh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','fatnassa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ain bazaz','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','hajar amor','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ain chemes','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','kasseb','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite ain el ghoula','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','lafarke','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite beja el jadida','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','nagachia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite belle vue','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','tarhouni','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite bir hofra','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite boutraa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite cnrps','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite de la police','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite de la sante 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite de la sante 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite des mimosas','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite des proffesseurs','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite des roses','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite dhamene','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite du gouvernorat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite echifa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite economie du nord','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite edhahbia 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite edhahbia 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el baraka','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el biadha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el boukhari','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el boustene','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9000','cite el habib','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9052','hammam sayala','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9021','mastouta','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9021','mastouta gare','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9021','sidi smail','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9023','cite el amel','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9023','el maagoula','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9029','sidi frej','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','briouig','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cheik el ouediane el guebli','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite des fonctionnaires','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite el hana','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite el izdihar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite el kamh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite essaada','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite essanabel','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite ezzouhour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','cite populaire','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','dour ismail','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','el fedhailia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','el gammarti','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','el ogla','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','ettraifa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','goubellat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','khacheb','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','khenguet eddihenne','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','tella','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','zone industrielle','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9083','grame','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9080','bir el euch','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9044','sidi nasser','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','cite de la poste','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','cite education','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','cite enfance','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','louatia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','oued ezzitoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9013','oued zarga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9034','sidi mediene','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','argoub ezzaatar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite baccar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite de la sante','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite des proffesseurs','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite dhamene','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite du gouvernorat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el azima 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el azima 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el azima 3','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el bahrine','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el behi','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el fateh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el ferdaous 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el hana','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9015','el ksar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el manar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite el menchari','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite erriadh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite essedk','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite ettadhamen','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite ezzouhour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite jallazia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','cite majerda','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','gueriche el oued','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','hidous','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','iden','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','mejez el bab','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9070','sidi ahmed jedidi','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9071','cite 02 mars','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9071','el griaat','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9072','chaouech','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9024','toukabeur','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9075','el herri','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','jemil','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','nefza','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','oued bouzenna','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','oued damous','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','ouled houimel','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','ouled kacem','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','oum laabid','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9011','tababa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','ain zakkar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','bou garnouna','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','el hemaidia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','el mecherga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','el oulija','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','ettaref','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','ezzouaraa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','ouechtata','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','ouled salem','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9012','zaga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','beni said','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite de la liberte','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite de la poste','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite des carrieres','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite des roses','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite el mhiri','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite erriadh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite essaada','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite ezzouhour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite independance','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite mixte','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite mohsen limam','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite rim','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','cite sidi saad','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','dar el hit','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','el amamria','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','el ayayada jamila','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','el mazdour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','fatnassa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9010','jbel diss','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','rihana','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','teboursouk','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9046','fadden essouk','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9032','borj brahim','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9032','douga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9032','khalled','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','ain el hammam','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','ain el kehoul','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','ain el melliti','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','ain jemmala','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','bir ettouta','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','bouzaida','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ain el karma','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ain mrad','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite de la republique','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite des martyrs','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite du stade','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite el bassatine','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite el glai','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite el gourjani','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite el hadj abdallah','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite el ksar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ennacim','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ennacim 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ennacim 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ezzayatine 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ezzayatine 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ibn khaldoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite ibn sina','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite industrielle','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite jardins','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite meska','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite oued essah','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','cite sidi bagga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','dougga rouines','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','el ayedh','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','el faouar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','el matria','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','naffet','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9040','ouled marai','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','ain younes','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite 20 mars','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite 26 fevrier','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite des andalous','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite el bassatine','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite el folla','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite el izdihar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite el malouf','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite ennacim','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite gharnata 1','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite gharnata 2','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite ibn zeidoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','cite spiniair','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','el glaa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','jlass bou issa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','mezougha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','oued jedra','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','bab bled','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','ouled slama','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite bahrnia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','rhiba','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite beharnia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','testour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite ben karouia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9060','zeldou','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite ben othman','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9061','esskhira','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite dar echabeb','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9061','henchir bou sofra','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite el gadhoum','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9062','ain tounga','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite el mendra','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite erraoudha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite essayadine','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite fedden jemaa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite jabbess','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite kichtilou','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite ouled slimane','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite sidi khouili','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite tafercha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','cite tijani','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','el mellah','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','esslouguia','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','jebel fellous','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9014','ouljet doukhane','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9042','ain eddefali','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9042','djebba','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9042','el henancha','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite 2 mars','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite commerciale','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite des ouvriers','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite el olfa','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite ennour','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite essalama','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite hached','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','cite ibn khaldoun','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','ennechima','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('9022','thibar','beja');
INSERT INTO locations (zipCode,city,state) VALUES ('2043','ben arous sud','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2013','ben arous','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite ben gamra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite ben joud','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite bou mhel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite boutouria','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite chebil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite de l''interieur','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite des juges','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite diar tounes','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el ahmadi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el amen','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el assil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el bassatine ancien','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el ferchichi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el iklil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el kenani','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el khalij','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el khalledi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el mahrajene 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el mahrajene 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el mouna','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite el wafa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite ennacim 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite ennacim 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite essafa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite essalem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite hlocationsich','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite jlassi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite mezriou','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite plein air','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite rabiaa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite snit','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','cite sprols','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence du mediterrane','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence el imara','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence ennacim','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence ezzouhour','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence sarra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','residence sirine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2097','bou mhel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el wifak','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ennakhil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ennarjes 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ennarjes 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ennasr 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ennasr 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite errachid 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite errachid 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite erraoudha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite erriadh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite erriadh 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite essalem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ibn jazzar 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite ibn mandhour','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite jardins','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite moncef bey','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite taher haddad','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite yargoula','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','el alia 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','el alia 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','el alia 3','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','el mourouj','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','la belle residence','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence chebbi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence chourouk 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence chourouk 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence chourouk 3','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence de l''horizon','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence de la verdure','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence du printemps','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence el foll','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence el khalil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence el mourjene','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence el ouard','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence el wafa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ennacim','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ennaoures','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ennesrine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence erraboua','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence essaad','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence essaada','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence essraya','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ibn khaldoun','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ibn zeidoun','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence ines','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence jinene el mourouj','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence meriem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence sidi bou said','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence type','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','residence zahret el mourouj','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite alyssa 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite alyssa 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite azza 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite azza 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite commerciale abou sofiane','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite commerciale boukhriss','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite des oasis','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el bassatine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el bochra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el faouz','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el foll','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2059','bir el kassaa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2074','cite el mourouj 3 bis','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite 18 janvier','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite borj louzir','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite du port','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite du wagon','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el ahlem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el akacia','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el amen','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el ezz','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el oulija','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite el ouns','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite ben miled','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite ennakhil 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite el habib','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite ennakhil 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite el houl','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite errachid','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite el ward','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite erriadh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite el yasmine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','cite ennasr','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite hedi khfacha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2065','ezzahra el habib','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite imen','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite industrielle','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite mrad 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite mrad 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','cite panorama','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2034','ezzahra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite 20 mars','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite brim','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite chebbi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el amel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el amel 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el banefsej','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el fateh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el hana','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el hidhab','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el izdihar','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el misk','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el moustakbel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el ward','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite el wifak','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite ennasr','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite ennouzha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite erriadh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite ezzitoun 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite khouaja','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite snit','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','cite trabelsi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','el menaychia','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','fouchana','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','meghira centre','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','meghira inzel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2082','zone industrielle el meghira','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1135','bir zendala','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1135','chebedda','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1135','douar el houch','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1135','naassen','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1164','hammam chatt','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2055','bir el bey','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2084','borj cedria','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite essanaoubria','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite hached','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite kortoba','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite mongi slim','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite office cereale','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite thermale','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','hammam lif','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2099','cite boussouffara','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2093','bou kornine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2093','cite bou kornine 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite 7 novembre','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite casino','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite dar el bey','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite de la municipalite','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite des instituteurs','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite des ouvriers','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite ennahdha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite ennasr','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2050','cite ennouzha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2033','megrine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2033','megrine coteau','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2033','megrine superieur','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2033','sidi rezig','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2024','megrine chaker','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2024','megrine jaouhara','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2014','cite founiz','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2014','megrine riadh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2014','saint gobin','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2014','zone industrielle saint gobin','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite bou akroucha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite bourbai','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite cebbalet chikh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite chaabane','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite chebbi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite de la carriere 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite de la carriere 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite du lycee','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el amen','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el atiq','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el baccouch','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el bassatine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el elmi 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el elmi 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el haddad','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el hana','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el ksar','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el omri 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite el omri 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ellouata','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ennacim 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ennacim 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ennasr','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ennouzha','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite erriadh','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite essaada 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite essaada 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite essaada 3','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite essalem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ettayari','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ettouahria','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite ezzitoun 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite fattouma bourguiba','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite hached 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite hached 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite jaouhara','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite jardins','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite mongi slim 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite mongi slim 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite oudhna','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite taieb mhiri','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','cite tnich','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','immeubles de l''interieur','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','mohamadia','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','residence el ferdaous','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','residence el moustakbel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','residence el ouns','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1145','residence ettaoufik','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','ahmed zaied','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','ben nouiji','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','borj essoufi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','bou jerdga','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','chala','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','chamine','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','cite ennasr','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','cite air nouvelle','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','douar la porte','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','cite ettayarane','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','douar salem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','el abebsa','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','el alelgua','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','el fendria','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','el araba','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','el kabouti','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','el haouamed','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','jebel ersass','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','el ksibi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','jourjou','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','ettiayra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','mirghna','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','ferme marquee','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2064','sidi salem el garci','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','henchir bouchta','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','henchir el ghobar','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','henchir khelil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','ain regad','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','huilerie bayrem','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','barrouta','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','mornag','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','bir jedid','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','ouzra','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','el gounna','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','sidi saad','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','henchir kharrouba','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','tarhouna 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','khelidia','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','tarhouna 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','kouenjel','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2090','zaouit mornag','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','sidi messaoud','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','sidi othman landari','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2054','sondage','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2044','errissala','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2063','nouvelle medina','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2096','el yasminette','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2018','cite snit','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2018','decouppage haj aleya','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2018','rades 7 novembre','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2018','village mediterranee','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2018','ville sportive','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','cite 20 mars','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','cite ennour','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','rades saline','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','chouchet rades','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','zone industrielle 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite mohamed ali','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','zone industrielle 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite rades 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('1125','zone petroliere','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite sfaxi','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite sncft','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite taieb mhiri 1','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite taieb mhiri 2','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','cite taieb mhiri 3','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','rades','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2040','rades plage','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','cite el ezz','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','cite nouvelle','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','rades el mrah','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','rades foret','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','rades medina','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','rades meliane','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('2098','rades mongil','ben arous');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite el korniche 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite de paris','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite el korniche 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite el hana','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite el korniche 3','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite ennacim','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite el morjene 3','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite erraouabi','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite el morjene 4','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','oued el marj','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite rafaha 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite rafaha 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7061','bizerte bab mateur','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','ennadhour','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','fejjet errih','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','ksar lahmar','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','marnissa','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','sidi ahmed','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7000','bizerte','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7000','cite ain mariem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7000','cite belvedere','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','cite bougatfa','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','cite de la municipalite','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','cite erriadh','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','cite hassen nouri','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','bizerte bougatfa','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','cite nouvelle plage','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite afh','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7001','ksiba','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite ain meriem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7002','cite militaire','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite bougatfa 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite chourouk sidi salem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7053','cite de la police','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7003','cite de la sante','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7064','bou zaria','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7071','bizerte hached','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7011','cite el mourouj','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7011','cite militaire','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7036','teskraya','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7011','la pecherie','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7027','methline','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','ain el berda','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','ain jenane','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7094','borj challouf','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7029','el mrazig','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7041','louata','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7081','ezzitoune','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7081','khetmine','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7093','sidi ali chebab','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7016','cite independance','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7016','el alia','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7016','el hariza','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7016','impasse ezzouhour','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7033','bajou','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7033','ghar el melh','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7024','touibia','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7024','zouaouine','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite 7 novembre','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite 9 avril','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite el amen','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite el mourouj','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite khaled ibn el walid','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','cite nouvelle','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7014','el aousja','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','ain rekoub','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','beni brahim','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','bou jrir','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','cite afh','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','cite borj deheb','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','cite rurale','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','cite snit','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','el atiba','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','el garia','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','el jafna','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','ghezala','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','henchir ettouila','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','laouilia','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','oued ezzitoun','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7040','ouled el may','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite erraja 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite erraja 3','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite errimel','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite errsass','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite escaliers','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite essadaka','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite gabsi','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite hamdoun','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite jaziri','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite lune','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite mohamed chehimi','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite nouvelle','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','jarzouna','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite ben arous','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite bouchoucha 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite calyptus','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite du soleil','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite ennacim','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7021','cite erraja 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7012','bazina','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7020','joumine','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7020','sayah','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7020','smadah','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','jebel ichkeul','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','mateur','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','sidi mansour','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','sidi nsir','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','souidia','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','tehent','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','borj el adouani','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','cite hached','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','ettaref','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','henchir el kahla','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','jabouz','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','mateur hached','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','oum jenna','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7022','sidi salem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite de la fraternite','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite de la gare','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite el manar','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite el omrane 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite el omrane 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite el omrane 3','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite el omrane 4','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','henchir el berna','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite ennahdha','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite ennasr','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite erraja 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite erraja 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite erraja 3','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite essadaka','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite ezzouhour','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite khemouma','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite montazah','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite snit','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','cite zarrouk','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7030','el aouana','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7072','menzel bourguiba ennajah','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7042','jouaouda','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','cite ben aleya','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','cite de la douane','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','cite la ruche','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','cite nouvelle','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','cite sidi yahya','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7050','menzel bourguiba','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite bir hmem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite chamelle','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite driss ben frej','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite el makarem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite ettahrir','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7026','cite 7 novembre','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite ettakaddoum','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7080','cite bir remel','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7026','cite des oranges','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','cite independance','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7080','cite el ahlem','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7026','cite el habib (el azib)','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','el ain el kebira','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7080','cite el baali','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7026','cite rurale 1','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7035','menzel abderrahman','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7080','cite el batan','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7026','cite rurale 2','bizerte');
INSERT INTO locations (zipCode,city,state) VALUES ('7080','cite el habib (menzel jemil)','bizerte');

