
CREATE TABLE saloons (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	code VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	is_primary BOOLEAN NOT NULL DEFAULT false,
	opening_date DATE,
	full_adr VARCHAR(255),
	email VARCHAR(255) DEFAULT '@gmail.com',
	location_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);



