
trigger:
- develop
- staging
- preprod
- master

pool:
  vmImage: ubuntu-latest

variables:
  SPRING_MAIL_USERNAME: $(SPRING_MAIL_USERNAME)
  SPRING_MAIL_PASSWORD: $(SPRING_MAIL_PASSWORD)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -DSPRING_MAIL_PASSWORD=$(SPRING_MAIL_PASSWORD)'


