
version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    restart: always
    networks:
      - net
  cita-backend-app:
    image: selimhorri/cita-backend-app:dev
    container_name: cita-backend-app
    ports:
      - 8400:8400
    environment:
      - APP_SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - APP_DB_NAME=${DB_NAME:-cita_db}
    depends_on:
      - zipkin
      - mysql
      - redis
      - elasticsearch
      - prometheus
    restart: always
    networks:
      - net
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-cita_db}
    volumes:
      - mysql-data:/var/lib/mysql/
    restart: always
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: always
    networks:
      - net
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    #volumes:
    #  - redis-data:/usr/local/etc/redis
    restart: always
    networks:
      - net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./:/etc/prometheus/
    restart: always
    networks:
      - net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    restart: always
    networks:
      - net
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - mysql
    #volumes:
    #  - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - net
  logstash:
    image: logstash:7.16.3
    #image: selimhorri/logstash-connector-j:7.16.3
    #image: dimmaryanto93/logstash-input-jdbc-mysql:6.6.0
    container_name: logstash
    #ports:
    #  - "5000:5000"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      #LOGSTASH_JDBC_URL: jdbc:mysql://mysql:3306/cita_staging
      #LOGSTASH_JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      #LOGSTASH_JDBC_DRIVER_JAR_LOCATION: mysql-connector-java-8.0.28.jar
      #LOGSTASH_JDBC_USERNAME: root
      #LOGSTASH_JDBC_PASSWORD: toor
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    restart: always
    networks:
      - net
  kibana:
    image: kibana:7.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - net

volumes:
  mysql-data:
    driver: local
  #mysql-secret:
  #  driver: local
  grafana-data:
    driver: local
  elasticsearch-data:
    driver: local
  redis-data:
    driver: local

networks:
  net:
    #driver: bridge
    name: cita-net






