
# https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html

version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - net
  cita-backend-app:
    image: selimhorri/cita-backend-app
    container_name: cita-backend-app
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./:/ect/prometheus/
    networks:
      - net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    networks:
      - net
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    #volumes:
      #- ./:/usr/share/elasticsearch/data
    networks:
      - net
  kibana:
    image: kibana:7.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - net
networks:
  net:
    driver: bridge





