
CREATE TABLE saloon_images (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	image_lob BLOB NOT NULL DEFAULT '',
	saloon_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);




