
app:
  security:
    jwt:
      secret-key: ${APP_SECURITY_JWT_SECRET_KEY:@app.security.jwt.secret-key@}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:3306/${DB_NAME:cita_staging_db}?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:toor}
  config:
    import:
      - 'optional:import/secrets/db-secrets.yml'
      - 'optional:import/secrets/jwt-secrets.yml'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/staging
  
logging:
  file:
    name: script/staging_log.log
    clean-history-on-start: true
  level:
    springframework:
      web: DEBUG
      data: DEBUG
    boot:
      autoconfigure:
        data:
          rest: DEBUG
          jpa: DEBUG
          orm: DEBUG

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import:
      - 'classpath:import/conf/k8s-config.yml'






