
server:
  servlet:
    context-path: /app

spring:
  application:
    name: CITA-BACKEND-APP
  profiles:
    active:
    - dev
  zipkin:
    base-url: http://${SPRING_ZIPKIN_BASE-URL:localhost}:9411/

management:
  endpoint:
    health:
      show-details: when-authorized









