
app:
  security:
    jwt:
      secret-key: ${APP_SECURITY_JWT_SECRET_KEY:@app.security.jwt.secret-key@}

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:3306/${DB_NAME:cita_preprod_db}?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:toor}
  config:
    import:
      - 'optional:import/secrets/db-secrets.yml'
      - 'optional:import/secrets/jwt-secrets.yml'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/preprod

logging:
  file:
    name: script/preprod_log.log
    clean-history-on-start: false
  level:
    springframework:
      web: INFO
      data: INFO
    boot:
      autoconfigure:
        data:
          rest: INFO
          jpa: INFO
          orm: INFO

---

spring:
  config:
    activate:
      on-cloud-platform: ${SPRING_CLOUD_ACTIVATE_ON_CLOUD_PLATFORM:kubernetes}
    import:
      - 'classpath:import/conf/k8s-config.yml'






