
server:
  port: 8400

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:3306/${MYSQL_DATABASE:cita_staging_db}?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:toor}
  config:
    import:
    - 'optional:secrets/db-secrets.yml'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations:
    - classpath:db/migration/staging
  
logging:
  file:
    name: script/staging_log.log
    clean-history-on-start: true
  level:
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG










