
spring:
  application:
    name: CITA-BACKEND-APP
  profiles:
    active:
    - dev
  zipkin:
    base-url: http://${SPRING_ZIPKIN_BASE-URL:localhost}:9411/
  jackson:
    serialization:
      indent-output: true

management:
  endpoint:
    health:
      show-details: when-authorized









