
app:
  security:
    secretKey: ${random.uuid}
  client:
    domains: http://localhost:4200/, http://cita-frontend-app:4200/

spring:
  application:
    name: CITA-BACKEND-APP
  profiles:
    active:
    - dev
  zipkin:
    base-url: http://${SPRING_ZIPKIN_BASE-URL:localhost}:9411/
#  elasticsearch:
#    uris:
#    - http://${SPRING_ELASTICSEARCH_HOST:localhost}:9200/
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
  jackson:
    serialization:
      indent-output: true
  jpa:
    open-in-view: false
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:cita.team.mail@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:CITA0123456789team}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

management:
  endpoint:
    health:
      show-details: when-authorized











