
apiVersion: v1
kind: Namespace
metadata:
  name: cita-prod-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: cita-prod-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: MYSQL_DATABASE

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: cita-prod-ns
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30002




