
apiVersion: v1
kind: Namespace
metadata:
  name: cita-dev-ns

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cita-prod-ns
type: Opaque
data:
  SPRING_MAIL_USERNAME: Y2l0YS50ZWFtLm1haWxAZ21haWwuY29t
  SPRING_MAIL_PASSWORD: Q0lUQTAxMjM0NTY3ODl0ZWFt




