
CREATE TABLE verification_tokens (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	token VARCHAR(255),
	expire_date TIMESTAMP,
	credential_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);



