
CREATE TABLE saloon_tags (
	saloon_id INT NOT NULL,
	tag_id INT NOT NULL,
	tagged_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	identifier VARCHAR(255) NOT NULL DEFAULT (UUID()),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (saloon_id, tag_id)
);



