
CREATE TABLE saloons (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	identifier VARCHAR(255) NOT NULL DEFAULT (UUID()),
	code VARCHAR(255) NOT NULL,
	tax_ref VARCHAR(255) NOT NULL DEFAULT '0000000X',
	name VARCHAR(255) NOT NULL,
	is_primary BOOLEAN NOT NULL DEFAULT false,
	opening_date DATE,
	full_adr VARCHAR(255),
	iframe_google_map TEXT,
	email VARCHAR(255) DEFAULT 'cita.team.mail@gmail.com',
	location_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);



