
CREATE TABLE credentials (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	identifier VARCHAR(255) NOT NULL DEFAULT (UUID()),
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL,
	is_enabled BOOLEAN NOT NULL DEFAULT false,
	is_account_non_expired BOOLEAN NOT NULL DEFAULT true,
	is_account_non_locked BOOLEAN NOT NULL DEFAULT true,
	is_credentials_non_expired BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);



