
CREATE TABLE user_images (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	identifier VARCHAR(255) NOT NULL DEFAULT RANDOM_UUID(),
	name VARCHAR(255),
	type VARCHAR(255) NOT NULL DEFAULT 'UNRECOGNIZED',
	size BIGINT NOT NULL DEFAULT 0,
	image_lob BLOB,
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT
);



