
CREATE TABLE user_images (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	image_lob BLOB,
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT
);



