
CREATE TABLE ratings (
	employee_id INT NOT NULL,
	customer_id INT NOT NULL,
	rate_date TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	rate DECIMAL(2, 1) NOT NULL,
	rate_description VARCHAR(255),
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	PRIMARY KEY (employee_id, customer_id, rate_date)
);



