
CREATE TABLE favourites (
	customer_id INT NOT NULL,
	saloon_id INT NOT NULL,
	favourite_date TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	identifier VARCHAR(255) NOT NULL DEFAULT RANDOM_UUID(),
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	PRIMARY KEY (customer_id, saloon_id)
);



