
CREATE TABLE saloon_images (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	image_lob BLOB NOT NULL DEFAULT '',
	saloon_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT,
	updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL NULL_TO_DEFAULT
);




